version: '3.8'

services:
  # 后端 API 服务
  api:
    build:
      context: ../project_back
      dockerfile: docker/Dockerfile
    container_name: myexam-api
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - DEBUG=false
      # ⚠️ 以下配置必须修改!
      - DATABASE_URL=mysql+pymysql://root:YOUR_DB_PASSWORD@db:3306/myexam_db
      - JWT_SECRET=YOUR_JWT_SECRET_KEY
      - JWT_EXPIRE_MINUTES=1440
      - ALLOW_ORIGINS=https://YOUR_DOMAIN
      - HEALTH_CHECK_URL=http://api:8000/api/v1/health
    volumes:
      - ../project_back/logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - myexam-network
    healthcheck:
      test: ["CMD", "python", "scripts/health/healthcheck.py"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  # MySQL 数据库
  db:
    image: mysql:8.0
    container_name: myexam-db
    environment:
      # ⚠️ 必须修改为强密码!
      - MYSQL_ROOT_PASSWORD=YOUR_DB_PASSWORD
      - MYSQL_DATABASE=myexam_db
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ../project_back/sql/00_init.sql:/docker-entrypoint-initdb.d/00_init.sql:ro
    restart: unless-stopped
    networks:
      - myexam-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pYOUR_DB_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  # 健康监控容器(每5分钟报活)
  health-monitor:
    build:
      context: ../project_back
      dockerfile: docker/Dockerfile
    container_name: myexam-health-monitor
    environment:
      - HEALTH_CHECK_URL=http://api:8000/api/v1/health
      # 可选: 外部监控 webhook
      # - HEALTH_WEBHOOK_URL=https://your-webhook.com/health
    command: ["python", "scripts/health/healthcheck.py", "monitor", "300"]
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - myexam-network

networks:
  myexam-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
